### ISSUE TITLE
Please modularize commons-collections4

### ISSUE THREAD

**Issue by jfallows** [GedMarc/JPMSPendingParent#1]
@GedMarc thanks for all your hard work on modularizing Apache Commons libraries. 👍 

Please include https://github.com/apache/commons-collections in your efforts. 🙏

**Comment by GedMarc** [comment]
@jfallows I can take a look, would you mind if I used my own parent? A couple of the plugins aren't resolving -- I can then also test central deploy's and jlink from my side 

From what I can see - it would really be as simple as copying the src/jre11 module info folder, and placing the moditect plugin into whichever profile you feel is best?

There doesn't look like any breaking changes

**Comment by jfallows** [comment]
@GedMarc thanks, that sounds great. 👍

We’ll need to figure out push the changes back in at some point though. 

Btw, just curious - why are you currently targeting Java11 instead of Java9 in the sources for the module info?

**Comment by GedMarc** [comment]
@jfallows I was figuring as the actual stable release, it's the better target, JDK9 isn't available anymore at all, and 10 required a lot of patch work for JTA layers and some of the stuff that was partially removed,

I can target JDK 9 and 10, but I do believe it is in discontinued status, the module-info's generally end up different to JDK 11 as well on topics of JAXB, JTA, JPA,. I see how these don't affect the commons toolkit but I guess it's something I've just started doing, 

Do you feel there is still a big need for support on JDK 9 and 10? JPMS implementation in the core pretty much only finalized in JRE11 :)

**Comment by GedMarc** [comment]
@jfallows So in the new maths4 module (Test dependency) there are a few snapshot dependencies that are failing when trying to publish to maven central on a release profile, I'm not sure I want to loosen my release constraints ;)

But collections and maths4 work just fine - If you're good with removing the maths4 dependency and those test classes in collections then awesome, I can then deploy through to maven central - 

There were a few test classes changed with regards to the Precision class (only), but no compile classes required changing.

These build into JLink just fine. 
If you think they'll accept the slight changes then I'll make a branch to do the pull request into the owning set

https://github.com/GedMarc/JPMSPendingParent

**Comment by GedMarc** [comment]
@jfallows Sorry, got my wires in a knot - it was lang3 as the dependency,

You can view/use the produced jar at https://search.maven.org/search?q=g:com.jwebmp.jpms.commons

**Comment by jfallows** [comment]
@GedMarc thanks for including `commons-collections4` in your efforts. 👍

**Comment by jfallows** [comment]
@GedMarc btw, i personally think it makes sense to depend on Java9 for `module-info.java` for cases where that is the minimum viable version of JDK where the module can run, then leave it up to the folks deploying their JVMs to make the decision on which compatible JDK version they prefer to use at runtime.

**Comment by GedMarc** [comment]
I'll give it some good thought :) 
If i'm not doing anything JTA or JMS  will definitely give it a good go, thanks for the advise!

**Comment by jfallows** [comment]
@GedMarc suggest using source folders named `src/main/java9` or `src/main/java11` alongside `src/main/java` (instead of the `src/jre11/java` pattern) as those `arc/main/javaN` sources will all be compiled and end up in the same `main` artifact JAR. Then a consistent approach can be followed for test sources in `src/test/java9` etc in projects where the `test` artifact is deployed during release and needs version specific classes in `META-INF/versions/....` of the `test` JAR.

**Comment by GedMarc** [comment]
@jfallows 
Ok, 
So I have tried that route a looong time ago, and unfortunately I have to say no. :( I'm really sorry man, experience has definitely shown me otherwise

Resources are also different, for example in Java9^ for services you don't create a file META-INF/services anymore. But for tests to execute properly (jupiter) they are still required to be found and run
Module info for tests in the module world is also a crash though, because you get duplicate class file error in compilation (tests can't have a different module-info, or I haven't figured out how yet, the compiler always blows out. 2 Years later I still have no solution to this problem).

By grouping code under main, and I imagine also resources? (resources/java9, resources/java11) you are really creating a problem - This is why I didn't go that route,

I don't think you should go that route either to be honest, I've gone through that train smash already and I'm kind of not willing to change over 200 projects to re-introduce the problem :)

**Comment by GedMarc** [comment]
@jfallows 

I believe to do what you want to do, you should annotate your tests with @DisabledOnJRE(JRE8) or the appropriate one?
https://junit.org/junit5/docs/5.3.0/api/org/junit/jupiter/api/condition/DisabledOnJre.html

I hope that helps!
